### PR TITLE
feat: Update asio to 1.34

### LINKED ISSUE #30: Build failure with asio 1.33 or newer due to removal of deprecated `asio::io_service`
tcp_pubsub does not build with newer versions of asio 1.33 (released 2024/12/4) or newer due to the [removal of the deprecated `asio::io_service`](https://github.com/chriskohlhoff/asio/commit/49fcd03434e8d43271522fe8d360558b5974ce83)

This results in many build errors such as:

```
/build/tcp_pubsub/src/tcp_pubsub-2.0.0/tcp_pubsub/src/publisher_session.h:39:50: error: ‘io_service’ is not a member of ‘asio’; did you mean ‘use_service’?
   39 |     PublisherSession(const std::shared_ptr<asio::io_service>&                               io_service
      |                                                  ^~~~~~~~~~
      |                                                  use_service
In file included from /build/tcp_pubsub/src/tcp_pubsub-2.0.0/tcp_pubsub/src/executor.cpp:9:
/build/tcp_pubsub/src/tcp_pubsub-2.0.0/tcp_pubsub/src/executor_impl.h:35:27: error: ‘io_service’ is not a member of ‘asio’; did you mean ‘use_service’?
   35 |     std::shared_ptr<asio::io_service> ioService()   const;
      |                           ^~~~~~~~~~
      |                           use_service
```

Given `io_service` was just an alias for `io_context` not much should need to change.

I shall work on a fix for it.

### PR DESCRIPTION
**Pull request by DownerCase**
Updates asio to 1.34 to resolve build failures when trying to use new versions.

I don't know why I had to increase the test timeout but I can reproduce the failure on master with the asio 1.32. :shrug: 

~~Nb: There is still use of deprecated functionality with the data strand `.wrap` function but it doesn't cause the build to fail.~~

- Substituted `.wrap` for `asio::bind_executor` and set the compile definition to disallow using deprecated functionality :smile: 

Closes #30

### CODE REVIEW

**Comment by DownerCase** [comment]
@FlorianReimold That should be everything. Would be good to get this and the CMake policy update merged and a new version tagged. I'm working on some packaging stuff currently (for the AUR) and need this repo to be asio 1.34 compatible. :smile:

File: tcp_pubsub/src/subscriber_session_impl.cpp [hunk 1]
```diff
@@ -465,7 +464,8 @@ namespace tcp_pubsub
                                                                   return;
                                                                 }
                                                                 me->synchronous_callback_(data_buffer, header);
-                                                              });
+                                                              },
+                                                              asio::get_associated_allocator(me->data_strand_));
```
Comment (FlorianReimold) [inline tcp_pubsub/src/subscriber_session_impl.cpp]: Why is this line of code necessary?

File: tcp_pubsub/src/subscriber_session_impl.cpp [hunk 2]
```diff
@@ -479,7 +479,8 @@ namespace tcp_pubsub
                                       me->data_strand_.post([me]()
                                                             {
                                                               me->readHeaderLength();
-                                                            });
+                                                            },
+                                                            asio::get_associated_allocator(me->data_strand_));
```
Comment (FlorianReimold) [inline tcp_pubsub/src/subscriber_session_impl.cpp]: Why is this line of code necessary?

File: tcp_pubsub/src/subscriber_session_impl.cpp [hunk 3]
```diff
@@ -498,7 +499,8 @@ namespace tcp_pubsub
     data_strand_.post([me = shared_from_this(), callback]()
                       {
                         me->synchronous_callback_ = callback;
-                      });
+                      },
+                      asio::get_associated_allocator(data_strand_));
```
Comment (FlorianReimold) [inline tcp_pubsub/src/subscriber_session_impl.cpp]: Why is this line of code necessary?

**Review by FlorianReimold — COMMENTED** [review]
@DownerCase: Thanks for taking care of this! I only stumbled across the `asio::get_associated_allocator` calls. Why do we need those? The returned allocator is not used.

File: tcp_pubsub/src/subscriber_session_impl.cpp (hunk 1 above)
Comment (DownerCase) [reply tcp_pubsub/src/subscriber_session_impl.cpp]: Because the remaining signatures of `io_context_strand::post` requires an allocator even though the function doesn't use it...

https://github.com/chriskohlhoff/asio/blob/a892f73dc96bfaf92db98a3fe219f920fad007ea/asio/include/asio/io_context_strand.hpp#L174-L193

Looking at the commit that removed the originally used function, it actually says to use `asio::post` which does not require an allocator.

https://github.com/chriskohlhoff/asio/commit/2f9c4ef57b54707cb6a02a06636c8242ce017f06#diff-a9951ef828e91a6ea4683ee5f1da1046abaefaa093db694a8a9825a098f50431

Thank you. I will make that change.

**Comment by DownerCase** [comment]
Ok @FlorianReimold all sorted again. Seems like asio was confusing the 2015 toolchain, didn't dig deep into why but the 2017 toolchain doesn't fail with the same code :shrug:

**Review by FlorianReimold — APPROVED** [review]

**Comment by FlorianReimold** [comment]
VS 2017 toolchain is fine. Asio probably now uses some C++17 features. `asio::post` is the way to go here, I didn't realize that the `get_associated_allocator` call were connected to that.
